# Generated by Django 2.2 on 2019-04-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190412_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='key',
            field=models.SlugField(default=2, max_length=100, unique=True, verbose_name='Nombre clave'),
            preserve_default=False,
        ),
    ]
